name: automation-exercise-actions
on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Style Check
        uses: psf/black@stable

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Generate Coverage
        run: coverage run --omit 'venv/*' -m pytest
      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v3
        with:
          path: .coverage
          retention-days: 1

  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
            cache: 'pip'
      - name: Install Requirements
        run: pip install coverage
      - name: Download Coverage
        uses: actions/download-artifact@v3
        with:
          name: .coverage
      - name: Print Coverage
        run: coverage report
      - name: Generate XML Coverage
        run: coverage xml
      - name: 'Upload XML Coverage'
        uses: actions/upload-artifact@v3
        with:
          path: coverage.xml
          retention-days: 14     
